[package]
name = "iced_taffy"
version = "0.1.0"
edition = "2021"
authors = [
    "Nico Burns <nico@nicoburns.com>",
]
include = ["src/**/*", "Cargo.toml", "README.md"]
description = "Library for using Taffy layout with the Iced GUI framework."
repository = "https://github.com/nicoburns/iced_taffy"
keywords = ["cross-platform", "layout", "css-grid"]
categories = ["gui"]
license = "MIT"

[dependencies]
iced = { version = "0.7", features = ["image", "debug"] }
iced_native = { version = "0.8" }
taffy = { git = "https://github.com/nicoburns/taffy.git", rev = "bb3bb235d665cb899c47d1dceff4105e78fd72b0" }
